sonar.projectKey=RominaRamon10_lab-github-actions-t02
sonar.organization=rominaramon10

sonar.sources=.
sonar.exclusions=**/*.md,**/.github/**

# Esperar el resultado del Quality Gate: si falla, el job falla
sonar.qualitygate.wait=true
